### ISSUE TITLE
Having some issues using the provider to create a service

### ISSUE THREAD

**Issue by alexpopaconst** [pulumi/pulumi-kong#89]
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details

Hello! I am trying to use a provider and pass it to a service in order for the creation of the service to use the provider details( auth and admin uri), but I am getting a "401 Invalid credentials. Token or User credentials required" error back. It might be that I am wrongly assuming how this works, but here is my code:

### Steps to reproduce

1. Deploy this 
```
  const provider = new kong.Provider('kong-provider', {
    kongAdminUri: "config_uri",
    kongAdminToken: "token",
  });

  const service = new kong.Service(
    'service',
    {
      connectTimeout: 1000,
      host: 'test.org',
      path: '/mypath',
      port: 443,
      protocol: 'https',
      readTimeout: 3000,
      retries: 5,
      writeTimeout: 2000,
    },
    { provider }
  );
```

Expected: The service would use the provider and get created successfully.
Actual: 401 Invalid credentials. Token or User credentials required

**Comment by alexpopaconst** [comment]
Does anyone have any ideas on this?

**Comment by chris-aeviator** [comment]
I'm just exploring pulumi and evaluate if kong can be part of my solution. It is mentioned that 

> The Kong provider must be configured with credentials to deploy and update resources in Mailgun.

This seemed confusing to me at first, but looking deeper into the documentation of Kong (which is not opensource Kuma btw) requires 

> kong:kongAdminToken - API key used to secure the kong admin API in the Enterprise Edition. May be set via the KONG_ADMIN_TOKEN environment variable.

**Comment by alexpopaconst** [comment]
Finally found out the issue was that I needed to add the `kongAdminUsername` as well to the Provider. I guess I was expecting the usage to be the same as calling the config API manually, there the "kong-admin-api" is enough. 
Silly mistake.
